version: '3.5'

services:

  gateway:   
    build:
      context: .
      dockerfile: ./api-gateway/Dockerfile
      platforms: 
        - "linux/amd64"
    env_file:
      - .env
    volumes:
      - "./api-gateway/logs:/logs"
    ports:
      - ${GATEWAY_PORT}:${GATEWAY_PORT}
  
  ocr-engine:   
    build:
      context: .
      dockerfile: ./ocr-engine/Dockerfile
    env_file:
      - .env
    ports:
      - ${OCR_ENGINE_PORT}:${OCR_ENGINE_PORT}
    volumes:
      - ./ocr-engine/images:/app/images

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_SECRET}
    volumes:
      - mongodb_data:/data/db
  
  save-img:   
    build:
      context: .
      dockerfile: ./saveIMG/Dockerfile
    env_file:
      - .env
    ports:
      - ${SAVE_IMG_PORT}:${SAVE_IMG_PORT}
    volumes:
      - ./saveIMG/images:/images

volumes:
  mongodb_data: